expat_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '{{ env_var("DUCKDB_LOCATION") }}'
      schema: analytics_dev
      threads: 1

    prod:
      type: duckdb
      path: '{{ env_var("DUCKDB_LOCATION") }}'
      schema: analytics
      threads: 4
