version: 2

sources:
  - name: numbeo
    database: dwh
    schema: raw_numbeo
    tables:
      - name: cost_of_living
      - name: cost_of_living__data

  - name: forex
    database: dwh
    schema: raw_forex
    tables:
      - name: forex_daily

  - name: cities
    database: dwh
    schema: raw_cities
    tables:
      - name: cities
  - name: earnings
    database: dwh
    schema: raw_earnings
    tables:
      - name: job_info
