cities:
  - name: Munich
  - name: Berlin
  - name: Madrid
  - name: New York
  - name: Milan
  - name: Barcelona
  - name: Los Angeles
  - name: Chicago
  - name: London
  - name: Bangkok
  - name: Kuala Lumpur
  - name: Singapore
  - name: Valencia