cities:
- Munich
- Berlin
- Madrid
- New York
- Milan
- Barcelona
- Los Angeles
- Chicago
- London
- Bangkok
- Kuala Lumpur
- Singapore
- Valencia
- Mexico City
- Rome
jobs:
- job_title: Senior Data Engineer
  years_experience: 7.0
- job_title: Software Engineer
  years_experience: 5.0
- job_title: Performance Marketing Manager
  years_experience: 5.0
- job_title: Data Scientist
  years_experience: 10.0
- job_title: Sales Rep
  years_experience: 4.0
- job_title: Junior Product Manager
  years_experience: 2.0
